const {
  REACT_APP_FIREBASE_APIKEY,
  REACT_APP_FIREBASE_AUTHDOMAIN,
  REACT_APP_FIREBASE_PROJECTID,
  REACT_APP_FIREBASE_STORAGEBUCKET,
  REACT_APP_FIREBASE_MESSAGINGSENDERID,
  REACT_APP_FIREBASE_APPID,
  REACT_APP_FIREBASE_MEASUREMENTID,
} = {
  REACT_APP_FIREBASE_APIKEY: "AIzaSyBlguR0aN3CmozbwbH03T3WM_CNA6Gjiwc",
  REACT_APP_FIREBASE_AUTHDOMAIN: "is4261.firebaseapp.com",
  REACT_APP_FIREBASE_PROJECTID: "is4261",
  REACT_APP_FIREBASE_STORAGEBUCKET: "is4261.appspot.com",
  REACT_APP_FIREBASE_MESSAGINGSENDERID: "808274074688",
  REACT_APP_FIREBASE_APPID: "1:808274074688:web:5065d5ca0645b6e41293a5",
  REACT_APP_FIREBASE_MEASUREMENTID: "G-S636RREEHZ",
};

const firebaseConfig = {
  apiKey: REACT_APP_FIREBASE_APIKEY,
  authDomain: REACT_APP_FIREBASE_AUTHDOMAIN,
  projectId: REACT_APP_FIREBASE_PROJECTID,
  storageBucket: REACT_APP_FIREBASE_STORAGEBUCKET,
  messagingSenderId: REACT_APP_FIREBASE_MESSAGINGSENDERID,
  appId: REACT_APP_FIREBASE_APPID,
  measurementId: REACT_APP_FIREBASE_MEASUREMENTID,
};

export default firebaseConfig;
