export const UPDATE_GROUP_MEMBER_MODULES = "UPDATE_GROUP_MEMBER_MODULES";

export const ADD_GROUP_MEMBER = "ADD_GROUP_MEMBER";
export const DELETE_GROUP_MEMBER = "DELETE_GROUP_MEMBER";
export const UPDATE_GROUP_MEMBER = "UPDATE_GROUP_MEMBER";

export const ADD_GROUP = "ADD_GROUP";
export const DELETE_GROUP = "DELETE_GROUP";
export const UPDATE_GROUP = "UPDATE_GROUP";
